title: Meredith Cook
description: > # this means to ignore newlines until "baseurl:"
  This is Meredith Cook's personal website in which she hones her writing skills about a random assortment of things. Topics include Christian living, parenting, theology, and missions. 
permalink: 'pretty'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://meredithcook.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Meredith Cook # add your name
author-img: meredith-headshot.jpg # add your photo
about-author: Welcome! My name is Meredith Cook. I am married to  <a href="http://keelancook.com">this guy</a> and mom of two. I'm the Grant Coordinator for Southeastern Baptist Theological Seminary. I also graduated from there with an M. Div in Missiology. I write about Christian living, parenting, theology, and missions. # add description
social-twitter: meredithcook716 # add your Twitter handle
social-github: meredithcook # add your Github handle
social-linkedin: meredithcook716 # add your Linkedin handle
social-email: meredithcook716@gmail.com #add your email address
# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: G-DHPTC39GDF # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
