title: Meredith Cook
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: 'pretty'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://meredithcook.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Meredith Cook # add your name
author-img: MeredithCook_FAD_Headshot_Web-2.jpg # add your photo
about-author: Welcome! My name is Meredith Cook. I'm married to Keelan and mom of two. I am the content manager for The Upstream Collective and have an M.Div in Missiology from Southeastern Baptist Theological Seminary. I write about a random assortment of things. I like coffee, baking, and Gamecock football.   # add description
social-twitter: meredithcook716 # add your Twitter handle
social-github: meredithcook # add your Github handle
social-linkedin: meredithcook716 # add your Linkedin handle
social-email: meredithcook716@gmail.com #add your email address
# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: G-DHPTC39GDF # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
